### ISSUE TITLE
Morning session code review

### ISSUE THREAD

**Issue by henokkhm** [cosywasswa/My-Portfolio-Desktop#5]
In this code review, we suggest making the following improvements:

- Make the close button of the mobile menu smaller in accordance with the Figma design. Further, I think you should increase the margin-top of the button because it is too close to the top of the viewport. In the Figma design, there is more space.
- Please add **alt** attributes to social media icons, for accessibility reasons.

**Comment by cosywasswa** [comment]
Completed
